services:
  progettofia-app:
    build: .
    image: progettofia-app
    container_name: progettofia-container
    stdin_open: true # Equivalent to -i
    tty: true        # Equivalent to -t
    volumes:
      - ./output:/app/output
      - ./contenitore csv:/app/contenitore csv
    restart: "no"
